# Generated by Django 6.0.4 on 2026-04-10 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('repository_url', models.URLField(blank=True)),
                ('framework', models.CharField(default='Angular', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('target_value', models.FloatField()),
                ('unit', models.CharField(default='ms', max_length=20)),
                ('test_type', models.CharField(choices=[('smoke', 'Smoke'), ('load', 'Load'), ('stress', 'Stress'), ('spike', 'Spike'), ('web_vitals', 'Web Vitals')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_baselines', to='metrics.project')),
            ],
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('jest', 'Jest'), ('eslint', 'ESLint'), ('qa-agent', 'QA Agent'), ('ci', 'CI Pipeline'), ('manual', 'Manual')], max_length=50)),
                ('data_source', models.CharField(default='VERIFIED', max_length=20)),
                ('raw_data', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='metrics.project')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='metrics.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('statements_pct', models.FloatField(default=0)),
                ('branches_pct', models.FloatField(default=0)),
                ('functions_pct', models.FloatField(default=0)),
                ('lines_pct', models.FloatField(default=0)),
                ('total_lines', models.IntegerField(default=0)),
                ('covered_lines', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.metricsnapshot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_metrics', to='metrics.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CIPipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('running', 'Running'), ('pending', 'Pending')], max_length=20)),
                ('lint_status', models.CharField(default='pending', max_length=20)),
                ('test_status', models.CharField(default='pending', max_length=20)),
                ('build_status', models.CharField(default='pending', max_length=20)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('commit_sha', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='metrics.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('metric', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('>=', '>='), ('<=', '<='), ('==', '=='), ('<', '<'), ('>', '>')], max_length=5)),
                ('threshold', models.FloatField()),
                ('current_value', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning')], default='failed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_gates', to='metrics.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SecurityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=20)),
                ('owasp_category', models.CharField(blank=True, max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_findings', to='metrics.project')),
            ],
            options={
                'ordering': ['severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_smells', models.IntegerField(default=0)),
                ('complexity_issues', models.IntegerField(default=0)),
                ('duplication_pct', models.FloatField(default=0)),
                ('security_issues', models.IntegerField(default=0)),
                ('maintainability_rating', models.CharField(default='C', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_debts', to='metrics.project')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.metricsnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_name', models.CharField(max_length=200)),
                ('feature', models.CharField(blank=True, max_length=100)),
                ('total', models.IntegerField(default=0)),
                ('passed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('duration_ms', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='metrics.project')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.metricsnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
