# Generated by Django 6.0.5 on 2026-05-27 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Semi Senior'), ('senior', 'Senior')], default='mid', max_length=10, verbose_name='Nivel')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('github_username', models.CharField(blank=True, max_length=100, verbose_name='Usuario GitHub')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('joined_at', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
            ],
            options={
                'verbose_name': 'Desarrollador',
                'verbose_name_plural': 'Desarrolladores',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('end_date', models.DateField(verbose_name='Fecha fin')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: REQ-2426', max_length=50, unique=True, verbose_name='Código')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('type', models.CharField(choices=[('feature', 'Funcionalidad nueva'), ('bug', 'Corrección de bug'), ('tech_debt', 'Deuda técnica'), ('improvement', 'Mejora')], default='feature', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('todo', 'Por hacer'), ('in_progress', 'En desarrollo'), ('qa', 'En QA'), ('done', 'Entregado'), ('released', 'En producción')], default='todo', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateField(verbose_name='Fecha creación')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Fecha inicio desarrollo')),
                ('delivered_at', models.DateField(blank=True, help_text='Fecha en que el dev pasó el requerimiento a QA o cerró.', null=True, verbose_name='Fecha entrega')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='Fecha cierre')),
                ('qa_bounces', models.PositiveIntegerField(default=0, help_text='Cuántas veces volvió de QA al desarrollador.', verbose_name='Retornos de QA')),
                ('production_bugs', models.PositiveIntegerField(default=0, help_text='Bugs encontrados después del release.', verbose_name='Bugs en producción')),
                ('jira_url', models.URLField(blank=True, verbose_name='URL en Jira')),
                ('notes', models.TextField(blank=True, verbose_name='Notas / observaciones')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='developers.developer', verbose_name='Desarrollador asignado')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='developers.sprint', verbose_name='Sprint')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'ordering': ['-delivered_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('unit', 'Unitarias'), ('integration', 'Integración'), ('api', 'API'), ('e2e', 'End-to-End')], max_length=20, verbose_name='Tipo de prueba')),
                ('total', models.PositiveIntegerField(verbose_name='Total pruebas')),
                ('passed', models.PositiveIntegerField(verbose_name='Pasaron')),
                ('executed_at', models.DateField(verbose_name='Fecha ejecución')),
                ('notes', models.TextField(blank=True, help_text='Ej: "Mayor fallo en validaciones de borde".', verbose_name='Observaciones')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='developers.requirement', verbose_name='Requerimiento')),
            ],
            options={
                'verbose_name': 'Ejecución de pruebas',
                'verbose_name_plural': 'Ejecuciones de pruebas',
                'ordering': ['requirement', 'test_type'],
                'unique_together': {('requirement', 'test_type')},
            },
        ),
    ]
