# Generated by Django 6.0.5 on 2026-05-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='is_documented',
            field=models.BooleanField(default=False, help_text='Marcar cuando exista documentación funcional/técnica del requerimiento.', verbose_name='Documentado'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='space',
            field=models.CharField(blank=True, help_text='Módulo funcional del producto (ej: TUTOR_VIRTUAL, AGENDA_COMERCIAL_V5).', max_length=100, verbose_name='Espacio / módulo'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='code',
            field=models.CharField(blank=True, help_text='Ej: REQ-2426. Si se deja vacío, se genera automáticamente como REQ-NNN.', max_length=50, unique=True, verbose_name='Código'),
        ),
    ]
