# Generated by Django 6.0.5 on 2026-05-27 21:35
# Editado manualmente para preservar las asignaciones existentes (developer FK -> developers M2M).
# Se usa un related_name temporal ('requirements_m2m_tmp') para evitar colisión de accessor
# inverso con el FK 'developer' (related_name='requirements') durante la transición.

from django.db import migrations, models


def copy_developer_to_developers(apps, schema_editor):
    """Copia la asignación FK (developer) al nuevo M2M (developers)."""
    Requirement = apps.get_model('developers', 'Requirement')
    for req in Requirement.objects.all():
        if req.developer_id:
            req.developers.add(req.developer_id)


def reverse_copy(apps, schema_editor):
    """Reversa: toma el primer dev del M2M y lo pone como FK."""
    Requirement = apps.get_model('developers', 'Requirement')
    for req in Requirement.objects.all():
        first = req.developers.first()
        if first:
            req.developer_id = first.id
            req.save(update_fields=['developer'])


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_requirement_is_documented_requirement_space_and_more'),
    ]

    operations = [
        # 1) Agregar el M2M con related_name temporal (coexiste con el FK sin chocar)
        migrations.AddField(
            model_name='requirement',
            name='developers',
            field=models.ManyToManyField(
                help_text='Uno o más desarrolladores que trabajaron en este requerimiento.',
                related_name='requirements_m2m_tmp',
                to='developers.developer',
                verbose_name='Desarrolladores asignados',
            ),
        ),
        # 2) Copiar datos FK -> M2M
        migrations.RunPython(copy_developer_to_developers, reverse_copy),
        # 3) Eliminar el FK viejo (libera el related_name 'requirements')
        migrations.RemoveField(
            model_name='requirement',
            name='developer',
        ),
        # 4) Renombrar el related_name del M2M al definitivo 'requirements'
        migrations.AlterField(
            model_name='requirement',
            name='developers',
            field=models.ManyToManyField(
                help_text='Uno o más desarrolladores que trabajaron en este requerimiento.',
                related_name='requirements',
                to='developers.developer',
                verbose_name='Desarrolladores asignados',
            ),
        ),
    ]
