# Generated by Django 6.0.5 on 2026-05-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_fk_to_m2m_developers'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='planned_end_date',
            field=models.DateField(blank=True, help_text='Fecha planificada de entrega (cronograma). Se compara contra la entrega real para la desviación.', null=True, verbose_name='Entrega planificada'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='planned_start_date',
            field=models.DateField(blank=True, help_text='Fecha planificada de inicio (según el cronograma).', null=True, verbose_name='Inicio planificado'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='delivered_at',
            field=models.DateField(blank=True, help_text='Fecha real de entrega. Desviación = entrega real − entrega planificada.', null=True, verbose_name='Entrega real'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='started_at',
            field=models.DateField(blank=True, help_text='Fecha real en que se empezó a desarrollar.', null=True, verbose_name='Inicio real'),
        ),
    ]
