# Generated by Django 6.0.5 on 2026-06-03 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_planned_dates_deviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Ej: HU-01, US-12. Opcional.', max_length=20, verbose_name='Código')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('todo', 'Por hacer'), ('in_progress', 'En desarrollo'), ('qa', 'En QA'), ('done', 'Entregada')], default='todo', max_length=20, verbose_name='Estado')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='Inicio planificado')),
                ('planned_end_date', models.DateField(blank=True, help_text='Se compara con la entrega real para la desviación.', null=True, verbose_name='Entrega planificada')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Inicio real')),
                ('delivered_at', models.DateField(blank=True, null=True, verbose_name='Entrega real')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='developers.requirement', verbose_name='Requerimiento')),
            ],
            options={
                'verbose_name': 'Historia de Usuario',
                'verbose_name_plural': 'Historias de Usuario',
                'ordering': ['requirement', 'code', 'id'],
            },
        ),
    ]
